language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/composer

sudo: false

addons:
  apt:
    packages:
      - parallel

before_install:
  - composer self-update
  - composer --version
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi

before_script:
  - export TYPO3_PATH_WEB=$PWD/.Build/Web
  - chmod +x ./.travis/*.sh

jobs:
  include:
    - stage: test
      script: ./.travis/test_phpcs.sh
      env: BUILD_TYPE="PHP code sniffer"
      php: 7.2

    - script: ./.travis/test_phpunit.sh
      php: 7.2
      env: BUILD_TYPE="Unit tests" TYPO3_VERSION="typo3/minimal=^9.3" UPLOAD_CODE_COVERAGE=yes
    - script: ./.travis/test_phpunit.sh
      php: 7.2
      env: BUILD_TYPE="Unit tests" TYPO3_VERSION="typo3/minimal=dev-master"

    - script: ./.travis/test_lint.sh
      php: 7.2
      env: BUILD_TYPE="PHP lint"

    - script: ./.travis/test_functional.sh
      php: 7.2
      env: BUILD_TYPE="Functional tests" TYPO3_VERSION="typo3/minimal=^9.3" NIMUT_TESTING_FRAMEWORK="nimut/testing-framework=dev-master"
    - script: ./.travis/test_functional.sh
      php: 7.2
      env: BUILD_TYPE="Functional tests" TYPO3_VERSION="typo3/minimal=dev-master" NIMUT_TESTING_FRAMEWORK="nimut/testing-framework=dev-master"

    - stage: deploy
      script: ./.travis/deploy_ter.sh
      env: BUILD_TYPE="TER upload"
      php: 7.1
